require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara

AllCops:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
  